csiwebsite/urls.py
#Importing Dependencies
from django.contrib import admin
from django.conf.urls import url, include
from django.urls import path

urlpatterns = [
    path('',include('homepage.urls'),name='home'), #Directs to the homepage!
    url(r'^admin/', admin.site.urls),
    url(r'^events/', include('event.urls')), #Directs to event app!
    url(r'^council/',include('members.urls')), #Directs to members app!
]

event/urls.py
#Importing Dependencies
from django.conf.urls import url
from . import views

urlpatterns = [
    #/events/
    url(r'^$', views.contact_form, name='events'),

    #/events/712/
    url(r'^(?P<event_id>[0-9]+)/$', views.detail, name='detail'),
]

event/models.py
#Import Dependencies
from django.db import models

class Event(models.Model):
    title = models.CharField(max_length = 250)
    title_picture = models.CharField(max_length = 1000)

    def __str__(self):
        return self.title

class EventDetail(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    event_title = models.CharField(max_length = 250)
    event_picture = models.CharField(max_length = 1000)
    description = models.CharField(max_length = 5000)

    def __str__(self):
        return self.event_title

event/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(label = 'name', max_length = 200)
    email = forms.EmailField(label = 'email' , max_length = 200)
    message = forms.CharField(label = 'message', widget=forms.Textarea)

event/views.py
#Import Dependencies
from django.http import Http404
from .models import Event
from django.template import loader
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .forms import ContactForm
import os
import gspread
from oauth2client.service_account import ServiceAccountCredentials
from oauth2client import service_account
import json


def contact_form(request):
    all_events = Event.objects.all()
    template = loader.get_template('event/index.html')
    if request.method =='POST':
        DIRNAME = os.path.dirname(__file__)
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get('name')
            email = form.cleaned_data.get('email')
            message = form.cleaned_data.get('message')
            scope = ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
            credentials = ServiceAccountCredentials.from_json_keyfile_name(os.path.join(DIRNAME,'credential.json'), scope)
            gs = gspread.authorize(credentials)
            wsheet = gs.open_by_url("https://docs.google.com/spreadsheets/d/1n3vAb3NeW-C1kr0_vgwiuSNCoQ3uc0jGyTBUjRozMmY/edit?usp=sharing").sheet1
            wsheet.append_row([name,email,message])
            return redirect("/events/")
        else:
            return HttpResponse("Fill the form!")

    form = ContactForm

    return render(
        request,'event/index.html',{
            "form":form,
            "all_events":all_events,
            }
    )


# def index(request):
#     all_events = Event.objects.all()
#     template = loader.get_template('event/index.html')
#     context = {
#         'all_events' : all_events,
#     }
#     return HttpResponse(template.render(context, request))

def detail(request, event_id):
    try:
        event = Event.objects.get(pk=event_id)
        template = 'event/event_detail.html'
        #context = {'event':event}
        form = ContactForm

        if request.method =='POST':
            DIRNAME = os.path.dirname(__file__)
            form = ContactForm(request.POST)
            if form.is_valid():
                name = form.cleaned_data.get('name')
                email = form.cleaned_data.get('email')
                message = form.cleaned_data.get('message')
                scope = ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']
                credentials = ServiceAccountCredentials.from_json_keyfile_name(os.path.join(DIRNAME,'credential.json'),scope)
                gs = gspread.authorize(credentials)
                wsheet = gs.open_by_url("https://docs.google.com/spreadsheets/d/1n3vAb3NeW-C1kr0_vgwiuSNCoQ3uc0jGyTBUjRozMmY/edit?usp=sharing").sheet1
                wsheet.append_row([name,email,message])
                return redirect("/events/" + str(event_id))
            else:
                return HttpResponse("Fill the form!")

        form = ContactForm


    except Event.DoesNotExist:
        raise Http404("Event does not exist")
    return render(request,template,{'event':event,'form':form})
    # return HttpResponse(template.render(context,request))

event/templates/event/base.html
{% load static %}
<!--
	Forty by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
<head>
    <title>Events</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
    <link rel="stylesheet" href="{% static 'event/assets/css/main.css' %}"/>
    <link rel="stylesheet" href="{% static 'event/assets/css/marginfix.css' %}"/>
    <noscript>
        <link rel="stylesheet" href="{% static 'event/assets/css/noscript.css' %}"/>
    </noscript>
</head>
<body class="is-preload">
<!-- Wrapper -->
<div id="wrapper">
    <!-- Header -->
    <!-- Note: The "styleN" class below should match that of the banner element. -->
    <header id="header" class="alt style2">
        <a href="{% url 'homepage' %}" class="logo"><strong>CSI-KJSCE</strong> <span>Students' Chapter</span></a>
        <nav>
            <a href="#menu">Menu</a>
        </nav>
    </header>

    <!-- Menu -->
    <nav id="menu">
        <ul class="links">
            <li><a href="{% url 'homepage' %}">Home</a></li>
            <li><a href="{% url 'members' %}">Council</a></li>
            <li><a href="{% url 'events' %}">Events</a></li>
        </ul>
        <ul class="actions stacked">

        </ul>
    </nav>
    <!-- Banner -->
    <!-- Note: The "styleN" class below should match that of the header element. -->
    <section id="banner" class="style2">
        <div class="inner">
							<span class="image">
								<img src="#" alt=""/>
							</span>
            <header class="major">
                <h1 style="color:white">Events Organized</h1>
            </header>
            <div class="content">
                <b><h4 style="color:white">We are what we repeatedly do.<br/>
                    Excellence, therefore is not an act, but a habit.</h4></b>
            </div>
        </div>
    </section>
    {% block body %}
    {% endblock %}
</div>
                <!-- Contact -->
                    <section id="contact">
                        <div class="inner">
                            <section>

                                <!-- <form method="post" action="#">
                                    <div class="fields">
                                        <div class="field half">
                                            <label for="name">Name</label>
                                            <input type="text" name="name" id="name" />
                                        </div>
                                        <div class="field half">
                                            <label for="email">Email</label>
                                            <input type="text" name="email" id="email" />
                                        </div>
                                        <div class="field">
                                            <label for="message">Message</label>
                                            <textarea name="message" id="message" rows="6"></textarea>
                                        </div>
                                    </div>
                                    <ul class="actions">
                                        <li><input type="submit" value="Send Message" class="primary" /></li>
                                        <li><input type="reset" value="Clear" /></li>
                                    </ul>
                                </form> -->
                                <form method="post" action="#">
                                        {% csrf_token %}
                                        {{ form }}
                                        <ul class="actions">
                                            <li><input type="submit" value="Send Message" class="primary" /></li>
                                            <li><input type="reset" value="Clear" /></li>
                                        </ul>
                                </form> 



                            </section>
                            <section class="split">
                                <section>
                                    <div class="contact-method">
                                        <span class="icon alt fa-envelope"></span>
                                        <h3>Email</h3>
                                        <a href="mailto:csi-kjsce@somaiya.edu">csi-kjsce@somaiya.edu</a>
                                    </div>
                                </section>
                                <section>
                                    <div class="contact-method">
                                        <span class="icon alt fa-phone"></span>
                                        <h3>Phone</h3>
                                        <span>(+91) <a href="tel:7738586795">7738586795</a></span>
                                    </div>
                                </section>
                                <section>
                                    <div class="contact-method">
                                        <span class="icon alt fa-home"></span>
                                        <h3>Address</h3>
                                        <span>CSI-KJSCE<br />
                                        KJ Somaiya College of Engineering<br />
                                        Vidyanagar, Vidyavihar<br />
                                        Mumbai, Maharashtra-400089</span>
                                    </div>
                                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3770.7776230055556!2d72.89735125069822!3d19.073512456943355!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3be7c627a20bcaa9%3A0xb2fd3bcfeac0052a!2sK.%20J.%20Somaiya%20College%20of%20Engineering!5e0!3m2!1sen!2sin!4v1569959696220!5m2!1sen!2sin" width="340" height="350" frameborder="100" style="border:0;" allowfullscreen=""style="align:left" class="google-map"></iframe>
                                </section>
                            </section>
                        </div>
                    </section>


<!-- Footer -->
<footer id="footer" style="margin-left: 30px; margin-top: 20px;">
    <div class="inner">
        <ul class="icons">
            <li><a href="https://twitter.com/CSI_KJSCE" class="icon alt fa fa-twitter"><span class="label">Twitter</span></a></li>
            <li><a href="https://www.facebook.com/csikjsomaiya/" class="icon alt fa-facebook"
                   class="icon alt fa-facebook"><span class="label">Facebook</span></a></li>
            <li><a href="https://www.instagram.com/csikjsce/?hl=en" class="icon alt fa-instagram"><span class="label">Instagram</span></a>
            </li>
            <li><a href="https://github.com/CSI-KJSCE" class="icon alt fa-github"><span class="label">GitHub</span></a>
            </li>
            <li><a href="https://www.linkedin.com/company/csi---kjsce-student%27s-chapter/"
                   class="icon alt fa-linkedin"><span class="label">LinkedIn</span></a></li>
        </ul>
        <ul class="copyright" >
            <li>&copy; Powered by CSI-KJSCE | 2018-19</li>
        </ul>
    </div>
</footer>


<!-- Scripts -->
<script src="{% static 'event/assets/js/jquery.min.js' %}"></script>
<script src="{% static 'event/assets/js/jquery.scrolly.min.js' %}"></script>
<script src="{% static 'event/assets/js/jquery.scrollex.min.js' %}"></script>
<script src="{% static 'event/assets/js/browser.min.js' %}"></script>
<script src="{% static 'event/assets/js/breakpoints.min.js' %}"></script>
<script src="{% static 'event/assets/js/util.js' %}"></script>
<script src="{% static 'event/assets/js/main.js' %}"></script>
</body>
</html>

event/templates/event/descriptionbase.html
{% load static %}
<!--
	Forty by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
<head>
    <title>Events</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"/>
    <link rel="stylesheet" href="{% static 'event/assets/css/main.css' %}"/>
    <noscript>
        <link rel="stylesheet" href="{% static 'event/assets/css/noscript.css' %}"/>
    </noscript>
</head>
<body class="is-preload">
<!-- Wrapper -->
<div id="wrapper">
    <!-- Header -->
    <!-- Note: The "styleN" class below should match that of the banner element. -->
    <header id="header" class="alt style2">
        <a href="{% url 'homepage' %}" class="logo"><strong>CSI-KJSCE</strong> <span>Students' Chapter</span></a>
        <nav>
            <a href="#menu">Menu</a>
        </nav>
    </header>

    <!-- Menu -->
    <nav id="menu">
        <ul class="links">
            <li><a href="{% url 'homepage' %}">Home</a></li>
            <li><a href="{% url 'members' %}">Council</a></li>
            <li><a href="{% url 'events' %}">Events</a></li>
        </ul>
        <ul class="actions stacked">

        </ul>
    </nav>
    <!-- Banner -->
    <!-- Note: The "styleN" class below should match that of the header element. -->
    <section id="banner" class="major">
        <div class="inner">
            <header class="major">
                <h1>{{ event.title }}</h1>
            </header>
            <div class="content">
                <p>From BUZZWORDS to BREAKTHROUGHS</p>
                <ul class="actions">
                    <li><a href="#one" class="button next scrolly">Glimpses!</a></li>
                </ul>
            </div>
        </div>
    </section>
    {% block body %}
    {% endblock %}
</div>
                <!-- Contact -->
                    <section id="contact">
                        <div class="inner">
                            <section>

                                <!-- <form method="post" action="#">
                                    <div class="fields">
                                        <div class="field half">
                                            <label for="name">Name</label>
                                            <input type="text" name="name" id="name" />
                                        </div>
                                        <div class="field half">
                                            <label for="email">Email</label>
                                            <input type="text" name="email" id="email" />
                                        </div>
                                        <div class="field">
                                            <label for="message">Message</label>
                                            <textarea name="message" id="message" rows="6"></textarea>
                                        </div>
                                    </div>
                                    <ul class="actions">
                                        <li><input type="submit" value="Send Message" class="primary" /></li>
                                        <li><input type="reset" value="Clear" /></li>
                                    </ul>
                                </form> -->
                                <form method="post" action="#">
                                        {% csrf_token %}
                                        {{ form }}
                                        <ul class="actions">
                                            <li><input type="submit" value="Send Message" class="primary" /></li>
                                            <li><input type="reset" value="Clear" /></li>
                                        </ul>
                                </form>
                                

                            </section>
                            <section class="split">
                                <section>
                                    <div class="contact-method">
                                        <span class="icon alt fa-envelope"></span>
                                        <h3>Email</h3>
                                        <a href="mailto:csi-kjsce@somaiya.edu">csi-kjsce@somaiya.edu</a>
                                    </div>
                                </section>
                                <section>
                                    <div class="contact-method">
                                        <span class="icon alt fa-phone"></span>
                                        <h3>Phone</h3>
                                        <span>(+91) <a href="tel:7738586795">7738586795</a></span>
                                    </div>
                                </section>
                                <section>
                                    <div class="contact-method">
                                        <span class="icon alt fa-home"></span>
                                        <h3>Address</h3>
                                        <span>CSI-KJSCE<br />
                                        KJ Somaiya College of Engineering<br />
                                        Vidyanagar, Vidyavihar<br />
                                        Mumbai, Maharashtra-400089</span>
                                    </div>
                                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3770.7776230055556!2d72.89735125069822!3d19.073512456943355!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3be7c627a20bcaa9%3A0xb2fd3bcfeac0052a!2sK.%20J.%20Somaiya%20College%20of%20Engineering!5e0!3m2!1sen!2sin!4v1569959696220!5m2!1sen!2sin" width="340" height="350" frameborder="100" style="border:0;" allowfullscreen=""style="align:left" class="google-map"></iframe>
                                </section>
                            </section>
                        </div>
                    </section>


<!-- Footer -->
<footer id="footer" style="margin-left: 30px; margin-top: 20px;">
    <div class="inner">
        <ul class="icons">
            <li><a href="https://twitter.com/CSI_KJSCE" class="icon alt fa fa-twitter"><span class="label">Twitter</span></a></li>
            <li><a href="https://www.facebook.com/csikjsomaiya/" class="icon alt fa-facebook"
                   class="icon alt fa-facebook"><span class="label">Facebook</span></a></li>
            <li><a href="https://www.instagram.com/csikjsce/?hl=en" class="icon alt fa-instagram"><span class="label">Instagram</span></a>
            </li>
            <li><a href="https://github.com/CSI-KJSCE" class="icon alt fa-github"><span class="label">GitHub</span></a>
            </li>
            <li><a href="https://www.linkedin.com/company/csi---kjsce-student%27s-chapter/"
                   class="icon alt fa-linkedin"><span class="label">LinkedIn</span></a></li>
        </ul>
        <ul class="copyright" >
            <li>&copy; Powered by CSI-KJSCE | 2018-19</li>
        </ul>
    </div>
</footer>

<!-- Scripts -->
<script src="{% static 'event/assets/js/jquery.min.js' %}"></script>
<script src="{% static 'event/assets/js/jquery.scrolly.min.js' %}"></script>
<script src="{% static 'event/assets/js/jquery.scrollex.min.js' %}"></script>
<script src="{% static 'event/assets/js/browser.min.js' %}"></script>
<script src="{% static 'event/assets/js/breakpoints.min.js' %}"></script>
<script src="{% static 'event/assets/js/util.js' %}"></script>
<script src="{% static 'event/assets/js/main.js' %}"></script>
</body>
</html>

event/templates/event/event_detail.html
{% extends 'event/descriptionbase.html' %}
{% block body %}
{% if event %}
<section id="one" class="spotlights">
    {% for event in event.eventdetail_set.all %}
    <section>
        <a href="{{ event.event_picture }}" class="image">
            <img src="{{ event.event_picture }}" alt="Cannot load img" data-position="center center"/>
        </a>
        <div class="content">
            <div class="inner">
                <header class="major">
                    <h3 style="color:white">{{ event.event_title }}</h3>
                </header>
                <ul class="actions">
                    <li><p>{{ event.description }}</p></li>
                </ul>
            </div>
        </div>
    </section>
    {% endfor %}
</section>
{% else %}
{% endif %}
{% endblock %}

event/templates/event/index.html
{% extends 'event/base.html' %}
{% block body %}
{% if all_events %}
<section id="two" class="spotlights">
    {% for event in all_events %}
    <section>
        <a href="{{ event.title_picture }}" class="image">
            <img src="{{ event.title_picture }}" alt="Cannot load img" data-position="center center"/>
        </a>
        <div class="content">
            <div class="inner">
                <header class="major">
                    <h3 style="color:white">{{ event.title }}</h3>
                </header>
                <ul class="actions">
                    <li><a href="{% url 'events' %}{{ event.id }}/" class="button" style="color:white">Learn more</a></li>
                </ul>
            </div>
        </div>
    </section>
    {% endfor %}
    </section>
{% else %}
    
{% endif %}
{% endblock %}